name: ci 
on:
  push:
    branches:
      - main
jobs:
  deploy:
    strategy:
        matrix:
          nix:
            - name: 2.10.3
              url: https://releases.nixos.org/nix/nix-2.10.3/install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force